service: api-recetas

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}

functions:
  analizarReceta:
    handler: handler.lambda_handler
    events:
      - httpApi:
          path: /recetas/analizar
          method: post
          cors: true

package:
  individually: true

custom:
  pythonRequirements:
    layer: true
    slim: true
    dockerizePip: true
